### ISSUE TITLE
I believe this should have been CUSBHostController instead of CUSBController

### ISSUE THREAD

**Issue by danielditlev** [smuehlst/circle-newlib#1]
At least I had to make that change for it to compile for me.

https://github.com/smuehlst/circle-newlib/blob/584d4c22e18665d204f4e4169ea29f8e86f6e2ad/libgloss/circle/io.cpp#L169C17-L169C31

**Comment by smuehlst** [comment]
How did you build circle-newlib? The only build that I'm testing and maintaining is as a submodule of https://github.com/smuehlst/circle-stdlib.

**Comment by smuehlst** [comment]
Please follow the build instructions for circle-stdlib: https://github.com/smuehlst/circle-stdlib#building-the-libraries
If something goes wrong then I will look into it.

**Comment by danielditlev** [comment]
My bad. I was on an earlier version for circle and circle-std. After having updated those to their current master it compiles.
